/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/model/L2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/L2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wall_1.geometry} material={nodes.wall_1.material} />
      <mesh geometry={nodes.rail_1.geometry} material={nodes.rail_1.material} />
    </group>
  )
}

useGLTF.preload('/L2.glb')
